### ISSUE TITLE
No effect of the redeployment after the first deployment

### ISSUE THREAD

**Issue by vinc1am** [Azure-Samples/cosmosdb-chatgpt#42]
I apologise for asking a silly question. I recently made some modifications to the frontend application. During the first deployment, the changes were successfully reflected in the application. However, subsequent deployments have not resulted in any visible changes to the application.

The below is the code to deploy/redeploy:
`az deployment group create --resource-group <resource-group-name> --template-file azuredeploy.bicep --mode Complete`

How I know the changes were not applied:
- First deployment: Changed the title to v0.1 (Reflected)
- Second deployment: Changed the title to v0.2 (Not reflected)

Many thanks!

**Comment by vinc1am** [comment]
Update: After deleting the App Service and App Service Plan, and redeploying it, the changes took effect.
However, may I know if this is the best practice for redeployment? 
Many thanks.

**Comment by markjbrown** [comment]
Changes to the front end of the application will not get deployed by ARM. ARM only redeploys changes between the template and the ARM resources.

If you modify the source of the application, go to Deployment Center and trigger a deployment from there. Or configure Azure Web Apps with CI-CD from GitHub.

Thanks!
